# Get sections by id
get http://localhost:8080/sections/86ba99b6-3a1b-49cc-8e15-5b7d4b0c68cc 
content-type: application/json
X-API-KEY: DwightSchrute

### Get schedules
get http://localhost:8080/schedules
content-type: application/json
X-API-KEY: DwightSchrute

### Get schedule for single id
get http://localhost:8080/schedules/e7f53160-0f6f-40c6-a244-a4de5125a504
content-type: application/json
X-API-KEY: DwightSchrute

### Get rooms
get http://localhost:8080/rooms
content-type: application/json
X-API-KEY: DwightSchrute